### ISSUE TITLE
Wedge in a little more PSIP information where possible

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#100]
PSIP is mentioned in the following places:
* Agile-redux slides 11-13
* Overview slides 19-20
* Summary slides 10-11

It would be nice to see if we can expand this a little, for example pointing out the https://RateYourProject.org tool and the progress tracking card catalog (which could be cast as examples).

**Comment by bernhold** [comment]
It would be nice to get this done for SC21.

**Comment by pagrubel** [comment]
It could fit nice in the overview. I was thinking we should at least have  the acronym PSIP there. I'm concerned about doing the overview in 20 minutes with more that 20 slides. I know some of the slides can be done quickly

**Comment by bernhold** [comment]
I understand the concerns.  Per the first comment, we do have PSIP in a couple of places, including overview. I'm thinking primarily at the link/sentence level rather than the slide level at this point.  I'll propose some amendments when I get a chance and ask you for feedback.

**Comment by pagrubel** [comment]
For what it is worth I felt something was missing on slide 20

**Comment by bernhold** [comment]
Suggestions welcome!

**Comment by bernhold** [comment]
Added links to RateYourProject and to the PTC catalog in all three talks.  Speakers shouldn't need to spend time on them, but they are more visible to the audience.
