### ISSUE TITLE
Where to put the agenda?

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#126]
Historically, the agenda for the specific tutorial event has been included in the presentations in various places...
1. Initially in the `intro` and then at the end of every presentation, annotated to indicate the current position in the agenda.  I discontinued this in large part because it was a lot of (error prone) work to generate the annotated agenda page for each presentation and them insert them all in their proper places.
2. Later, we transitioned to putting it only at the end of the `overview`, as a way of introducing what's coming up.  This more or less coincided with the advent of the tutorial website, so in principle, participants can reference the agenda at any time in their browser.
3. For ISC, Anshu put it at the end of `intro` instead of `overview`. Which I'm now thinking is a more natural place to put it.

I'd appreciate input from others on what they think works best.  Ideas that aren't listed above are also welcome.  And we do have the option of not including the agenda in the presentations at all, arguing that it is available on the website.

With your input, we can reach a decision and update the documentation accordingly.

**Comment by pagrubel** [comment]
At the end of the intro seems fine to me

**Comment by jarrah42** [comment]
I think it’s good to have it in the presentation. At the end of intro seems more natural to me.

**Comment by bernhold** [comment]
Okay, we'll put it at the end of the intro.  Need to update instructions.
