### ISSUE TITLE
Git Workflows: Refine focus of Git Workflows presentation

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#14]
IMHO, this talk needs provide a little more focus.  Git is too huge of a topic.  I believe the appropriate focus is on git and git workflows as a tool for team collaboration.  As such, I believe we should deemphasize the *mechanics* of pull requests, forks, and branches, and focus more on how these things can be used to facilitate collaboration.  And then the particular workflows should be described in terms of the collaborative model.

This is open to discussion, however.

**Comment by bernhold** [comment]
Should have a discussion and build a consensus on how to revise.

Jim: maybe evolve to a development workflows, Anshu 👍   "development workflows" is probably a better name
DavidR: great opportunity for examples, maybe video captures of interactions

**Comment by bernhold** [comment]
Relevant discussions in <https://github.com/bssw-tutorial/management/issues/10>
* <https://github.com/bssw-tutorial/management/issues/10#issuecomment-835794071>
* <https://github.com/bssw-tutorial/management/issues/10#issuecomment-835843389>
* <https://github.com/bssw-tutorial/management/issues/10#issuecomment-837032135>

**Comment by pagrubel** [comment]
Currently adding two CSE projects to the presentation to show how projects are collaborating. Since ISC has time for hands-on I'd like to leave the example using PR etc. slides. I may gloss through them to show what is coming.
