### ISSUE TITLE
Comments on collaborative-sw-dev

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#145]
It needs a high-level navigation slide at the beginning, and/or dividers between sections.  Currently the transitions are abrupt and it may not be clear to the participant where we're going.

Also, the agile material seems a bit out of order.  Maybe it was this way in previous editions, but I think we need to do a little bit more by way of introducing agile initially, and then moving into the slides that appear first currently.  Then on to kanban.

**Comment by pagrubel** [comment]
@bernhold I made some changes to hopefully satisfy this. Let me know what you think

**Comment by bernhold** [comment]
LGTM, thanks
