### ISSUE TITLE
Do we need to include release numbers in the presentations?

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#15]
Some of the labs are pretty particular about having presentations reviewed in advance.  Such reviews often generate a release number (exact terminology varies).  Two questions arise:
1) Do we need to actually display the release number *in the presentation*?  Or is it sufficient that one has been assigned?
2) If we do need to list it, where should it go?  Does it need to be on the first page?  Or can we include it on our "license" page, which is generally the second page of all of our presentations?

Please record the answers for each institution in a comment and check off your lab here.
- [x] LANL
- [ ] LLNL
- [x] SNL

**Comment by jwillenbring** [comment]
I try to add the SAND number (release number) to the second slide at the end of the disclaimer that is there for Sandia. I got a number for the recent tutorial and I wanted to add it to a "master copy" of the slides that someone would likely start with the next time we did a tutorial, but I wasn't sure how to do that. I did not want to change the "final version" for a previous tutorial, and the files in the general (not specific to an instance of a tutorial) were older and I didn't want to simply update those. Maybe we can discuss this at an upcoming meeting.

**Comment by bernhold** [comment]
@jwillenbring is the SAND number in some way reusable?  Do we need to get a new number every time?  What's the threshold for re-review?

**Comment by jwillenbring** [comment]
When a Sandian makes substantial changes, a new SAND number should be obtained. We should do this as a matter of process. If I get a new SAND number  and then someone else makes changes for the next tutorial, we would not request a new SAND number, but we should leave the existing one in the notes on the second slide.

**Comment by bernhold** [comment]
It sounds like these need to be visible in the presentation.  Because it is easy for them to get lost on the license/citation/acknowledgement slide, I believe they should be placed on the title slide, in the lower right corner.
