### ISSUE TITLE
pagrubel for 2023-11-12-sc: Update presentations by 2023-10-20

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#180]
- [x] "Update <https://github.com/bssw-tutorial/presentations/blob/master/collaborative-sw-dev.pptx> by 2023-10-20"
- [x] "Update <https://github.com/bssw-tutorial/presentations/blob/master/intro.pptx> by 2023-10-20"
- [x] "Update <https://github.com/bssw-tutorial/presentations/blob/master/overview.pptx> by 2023-10-20"
- [x] "Remember to update <https://github.com/bssw-tutorial/presentations/blob/master/presentations.yml if any titles change!"

**Comment by pagrubel** [comment]
Done! No real significant changes needed. Did some minor ones.
