### ISSUE TITLE
Decide whether or not to continue with Travis CI as the example CI service

### ISSUE THREAD

**Issue by jwillenbring** [bssw-tutorial/presentations#19]
CC: @markcmiller86

My understanding is that after Travis CI was bought out, the availability of cycles for open source code testing has changed dramatically. I skipped the hands on completely for the ECP AM and instead just showed some of the Travis example, and added a bit of content for GitHub Actions.

We should make a decision about what to do for future tutorials and update materials as necessary.

**Comment by bernhold** [comment]
I think this has been overtaken by events and propose to close.  Any objections?
