### ISSUE TITLE
CI: update examples at the end to match hands-on

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#23]
We need to move away from Travis.  So once we decide what we're going to do in the hands-on, we should make sure the presentation examples match.

See also <https://github.com/bssw-tutorial/management/issues/24>

**Comment by frobnitzem** [comment]
It seems like github-actions are free and easy to use: https://docs.github.com/en/actions/guides/setting-up-continuous-integration-using-workflow-templates
I want to write the testing hands-on with these.

**Comment by frobnitzem** [comment]
The presentation now uses github actions.  From my perspective updating these tickets - I'd rather have one ticket cover both the presentation and its associated hands-on material.  That way I can focus on the content.
