### ISSUE TITLE
Agile: update presentation for ISC

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#26]

**Comment by bernhold** [comment]
@rinkug  I suggest that you make sure that the hands-on content is up to date and delete the hands-on related slides from this presentation.

**Comment by bernhold** [comment]
Also, the section divider slides inherited from Mike's original version have a distorted version of the IDEAS logo.  Lois has asked that we fix this.  So I changed these to use the default section divider layout from the ECP template deck.  It is very simple, but it is consistent with the rest of the slides.  If you really feel that you must go back to the old section dividers, please talk to me so that we can get the logo fixed up.

**Comment by rinkug** [comment]
Uploaded  updated presentation. Also  removed hands-on slides. Left two scrum slides in there.
