### ISSUE TITLE
Should we use agenda slides in presentations? (please vote)

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#41]
Historically, I have leaned towards having the agenda slides at the end of each presentation to help participants navigate the overall tutorial.  However they take time to produce and insert and we don't think they're useful, I'd rather take a longer coffee break.

I will also note that now that we have the tutorial web site, each tutorial web page includes an agenda table that participants can call up at any time (e.g., <https://bssw-tutorial.github.io/events/2021-04-12-ecpam.html#agenda>).

So please use 👍 or 👎 reactions on this comment to vote for *keeping* agenda slides.  The button to provide a reaction is at the top *right* of this box.  The reactions appear in the lower left.  (How's that for consistency?)

**Comment by pagrubel** [comment]
Would you still have one agenda slide at the beginning?

**Comment by bernhold** [comment]
@pagrubel whatever we decide is important to do is fine.  If one is both necessary and sufficient, we can do that.  If we want one per presentation that's fine too.  Reducing our requirements just simplifies things a bit for me.

**Comment by pagrubel** [comment]
I hate to say no because I haven't produced those slides, but sure like having them

**Comment by bernhold** [comment]
Please answer based on what you think is best for the tutorial and the participants.  If we (I) *need* to do something to make it better, we should make every effort to do it.

**Comment by rinkug** [comment]
I think agenda slides are useful demarcations and I dont think they buy us too much time. 

As far as creating them goes, we could make it easy and put the same slide everywhere (instead of bolding the text for the specific section to be presented)

**Comment by bernhold** [comment]
There do not seem to be strong feelings either way.  Since I'm the one making and inserting the slides, I'm going to try simplifying things for a while -- probably one agenda slide for the Overview presentation, without details (that's what takes the time) and *not* trying to insert agendas as navigational aids.  We'll try it for a while and see how it goes.
