### ISSUE TITLE
Can we remove the lab management contract acknowledgements?

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#5]
The management contract acknowledgements on the license slide take up a lot of room.  After many years of believing that they were required on *papers* by ORNL and desired on presentations, I've discovered that apparently there is no such requirement, its just an urban legend.

So the question is whether any of the labs actually have a requirement for the management contract acknowledgement on presentations?
- [x] ANL -- no
- [ ] LANL
- [ ] LBNL (IDEAS member, but no participation in tutorials to date)
- [ ] LLNL
- [x] ORNL -- no
- [ ] SNL

**Comment by markcmiller86** [comment]
For LLNL, I believe this is *required* though they do offer a minimal word option...

```
Prepared by LLNL under Contract DE-AC52-07NA27344. LLNL-TYPE-XXXX
```

Where `LLNL-TYPE-XXXX` is an LLNL Information Management Document Release Identifier.

Perhaps if all lab's such verbiage could be gathered together on a single slide at the end, that could get it out of the main flow.

**Comment by bernhold** [comment]
@markcmiller86 I prefer to put the document release identifier (where required) on the *first* slide.

It allows the license/citation slide to be completely uniform across all presentations in the tutorial.  Which greatly simplifies dealing with that.

We do need to keep the license/citation slide for those two elements, as well as the funding ack to ECP.  I'm willing to consider moving it to the end, though, since we only bother to explain it in the intro module.

I would appreciate input from folks at the other labs as to whether the management contract ack is really required for them, or not.  @pagrubel, @jwillenbring ?

**Comment by bernhold** [comment]
I think the conclusion here is "no"

**Comment by pagrubel** [comment]
I'll check into that, but I haven't seen any anywhere, just in publications.

**Comment by bernhold** [comment]
Well, right now we put them all on page 2 and skip past it in presentation.  Page 2 also has the license and preferred citation, though the acknowledgments are the bulk of the space.

If we have to keep them, I think I'd prefer they stay on page 2 rather than pushing to the end.  The title slide refers to the license, citation, and acknowledgments slide as "slide 2" but if that slide goes to the end, that slide number is constantly changing and becomes a maintenance nightmare (maybe we could say "last slide").

And when we have R&R numbers (LLNL, SNL, or LANL seem to be the only labs that are rigorous about R&R), we put those on the title slide.  My recollection is that someone from one of those labs told me they needed to be on the title slide.

**Comment by pagrubel** [comment]
LANL does not need the contract information. 
I still think the LA-UR needs to be on the title slide of a presentation when I am the presenter, and it can be the same one if the material hasn't changed significantly.
