### ISSUE TITLE
Reproducibility, Testing (which?): discuss testing of 3rd party dependencies

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#59]
Testing of (key) third-party dependencies can be important for code verification, reproducibility, and generally having confidence in your code.  It would be worth add mentions of this to the Reproducibility presentation and the appropriate Testing presentation (not sure which one).

**Comment by bernhold** [comment]
Added to Reproducibility

**Comment by frobnitzem** [comment]
I added a note about "upstream dependencies" to testing-introduction.
