### ISSUE TITLE
Suggested changes to git-workflows from ATPESC 2021

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#97]
We should add some material about peer review of pull requests as another collaborative workflow concept that git-based hosting platforms offer.

Jeff Carver and Nasir Eisty have done work on peer code review in scientific software settings, and it might be useful to consult them and their work for possible enhancements once we have some basic content in place.

**Comment by pagrubel** [comment]
Found this blog which may be helpful:
https://blog.codacy.com/how-to-code-review-in-a-pull-request/

**Comment by pagrubel** [comment]
@bernhold  I added 2 slides on code review, please look at slides 16 & 17

**Comment by bernhold** [comment]
@pagrubel looks like a good start.  We'll see what kind of feedback we get from it.

I would ask for a couple of small changes...
* On 16 please put the title consistently in title case
* On 17 please put the main bullet in sentence case "Helpful practices..."
