### ISSUE TITLE
Suggested changed to continuous-integration from ATPESC 2021

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/presentations#99]
* Slides 16-18 have animations that seem superfluous.  When @frobnitzem presented, he didn't use them.  It seems like the animated elements could be displayed statically and it would be fine.
* Slide 17 in two of the three animation steps, the text seems to be hidden behind the code.  If we keep the animations, those elements at least need to be brought forward.
* If slides 23-26 remain unused (hidden) they should be moved to the -extra companion file

**Comment by jarrah42** [comment]
I've reviewed the slides and made a few clarifications. I've also de-emphasized Travis due to concerns with it's viability. I'll take a look at David's comments next.
